type: error
post:
  description: |
    <h2>Starts orders</h2>
    <p>this resource can be used in the GUI for three functions</p>
    <ul>
    <li><i>start immediatly</i></li>
    <li><i>start at</i> (with ``at``)</li>
    <li><i>start at parametrised</i> (with ``at`` and ``params``)</li>
    </ul>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="16%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``jobschedulerId``</td><td>required, string</td><td>JobScheduler Master ID</td><td>scheduler</td><td></td></tr>
    <tr><td>``orders``</td><td>required, array</td>
    <td>Specified the orders which should be modified.</td>
    <td> [{
      <div style="padding-left:10px;">"jobChain":"/sos/reporting/Inventory",</div>
      <div style="padding-left:10px;">"orderId":"Inventory"</div>
      <div style="padding-left:10px;">"at":"now+10"</div>
      }]</td>
    <td></td></tr>
    <tr><td>``at``</td><td>optional, string<br/>field of each ``orders`` item</td>
    <td>start time in ISO format yyyy-mm-dd HH:MM[:SS] or now or now + HH:MM[:SS] or now + SECONDS</td>
    <td>now+10</td><td>now</td></tr>
    <tr><td>``timeZone``</td><td>optional, string<br/>field of each ``orders`` item</td><td><ul>
       <li>This parameter set the time zone for an absolute time stamp in the ``at`` parameter.</li>
       <li>This parameter is ignored for relative times in ``at`` such as "now+10"</li>
       <li>See here the list for <a href="https://en.wikipedia.org/wiki/List_of_tz_database_timeZones">available time zones</a>.</li>
    </ul></td><td>Berlin/Europe</td><td>Time zone of the JobScheduler</td></tr>
    <tr><td>``state``</td><td>optional, string<br/>field of each ``orders`` item</td><td>Name of the desired job chain start node</td><td></td><td></td></tr>
    <tr><td>``endState``</td><td>optional, string<br/>field of each ``orders`` item</td><td>Name of the desired job chain end node</td><td></td><td></td></tr>
    <tr><td>``params``</td><td>optional, array<br/>field of each ``orders`` item</td><td>Parameter</td><td>params:[{"name":"...","value":"..."}]</td><td></td></tr>
    <<audit>>
    </tbody></table>

  body:
    application/json:
      schema: modifyOrders
      example: |
        {
          "jobschedulerId": "scheduler",
          "orders": [{
            "orderId": "order1",
            "jobChain": "/test/testJobChain",
            "at": "now"
          }, {
            "orderId": "order2",
            "jobChain": "/test/testJobChain",
            "at": "now"
          }, {
            "orderId": "order3",
            "jobChain": "/test/testJobChain",
            "at": "now"
          }, {
            "orderId": "order4",
            "jobChain": "/test/testJobChain",
            "at": "now"
          }, {
            "orderId": "order5",
            "jobChain": "/test/testJobChain",
            "at": "now"
          }]
        }
  responses:
    200:
      description: It returns an _ok_. This reply code comes only for bulk operations if all commands were successful.
      body:
        application/json:
          schema: ok
          example: |
            {
              "deliveryDate":"2016-05-05T21:13:35Z",
              "surveyDate":"2016-05-05T21:13:34Z",
              "ok":true
            }
    419:
