get:
  description: |
    <h2>Send custom logo settings</h2>
  responses:
    200:
      body:
        application/json:
          schema: logo
          example: |
            {
              "name": "myLogo.png",
              "width": "100%",
              "height": "100%",
              "position": "top:20%"
            }
post:
  description: |
    <h2>Send custom logo settings</h2>
  responses:
    200:
      body:
        application/json:
          schema: logo
          example: |
            {
              "name": "myLogo.png",
              "width": "100%",
              "height": "100%",
              "position": "top:20%"
            }