type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    
  body:
    application/json:
      schema: <<schema>>
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          example: <<example200>>
          schema: <<schema200>>
    420:
      body:
        application/json:
