type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``jobschedulerId``</td><td>required, string</td><td>JobScheduler Master ID</td><td>scheduler</td><td></td></tr>
    <tr><td>``nodes``</td><td>required, array</td>
    <td>Restricts request by a collection of nodes specified by its jobChain and node name</td>
    <td> [{
      <div style="padding-left:10px;">"jobChain":"/sos/reporting/Inventory"</div>
      <div style="padding-left:10px;">"node":"inventory"</div>
      }]</td>
    <td></td></tr>
    <<audit>>
    </tbody></table>
  body:
    application/json:
      schema: modifyNode
      example: |
        {
          "jobschedulerId": "scheduler",
          "nodes": [
            {
              "jobChain": "/sos/reporting/Inventory",
              "node": "inventory"
            }
          ]
        }
  responses:
    200:
      description: |
        **Confirm <span style="text-transform: capitalize;"><<resourcePathName>></span> successfully**
      body:
        application/json:
          example: |
            {
              "deliveryDate":"2016-05-05T21:13:35Z",
              "ok":true
            }
          schema: ok
    419:
      body:
        application/json:
