package com.sos.joc.xmleditor.impl;

import java.io.StringReader;
import java.nio.file.Files;
import java.util.Collections;
import java.util.Date;
import java.util.Map;

import javax.ws.rs.Path;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.InputSource;

import com.sos.DataExchange.converter.JadeXml2IniConverter;
import com.sos.auth.rest.permission.model.SOSPermissionJocCockpit;
import com.sos.hibernate.classes.SOSHibernateSession;
import com.sos.jitl.reporting.db.DBItemAuditLog;
import com.sos.jitl.reporting.db.DBItemXmlEditorObject;
import com.sos.jitl.xmleditor.common.JobSchedulerXmlEditor;
import com.sos.jitl.xmleditor.db.DbLayerXmlEditor;
import com.sos.joc.Globals;
import com.sos.joc.classes.JOCDefaultResponse;
import com.sos.joc.classes.JOCHotFolder;
import com.sos.joc.classes.JOCResourceImpl;
import com.sos.joc.classes.audit.XmlEditorAudit;
import com.sos.joc.classes.xmleditor.JocXmlEditor;
import com.sos.joc.classes.xmleditor.exceptions.XsdValidatorException;
import com.sos.joc.classes.xmleditor.validator.XsdValidator;
import com.sos.joc.exceptions.JobSchedulerBadRequestException;
import com.sos.joc.exceptions.JocError;
import com.sos.joc.exceptions.JocException;
import com.sos.joc.model.xmleditor.common.AnswerMessage;
import com.sos.joc.model.xmleditor.common.ObjectType;
import com.sos.joc.model.xmleditor.deploy.DeployConfiguration;
import com.sos.joc.model.xmleditor.deploy.DeployConfigurationAnswer;
import com.sos.joc.xmleditor.resource.IDeployResource;
import com.sos.schema.JsonValidator;

import sos.util.SOSDate;

@Path(JocXmlEditor.APPLICATION_PATH)
public class DeployResourceImpl extends JOCResourceImpl implements IDeployResource {

    private static final Logger LOGGER = LoggerFactory.getLogger(DeployResourceImpl.class);

    private static final String DEPLOY_HEADER = "Automatically generated file (%s UTC).";
    private static final String DEPLOY_HEADER_MESSAGE =
            "Do not make any changes to this file, as it has been automatically generated by the JOC %s Configuration and will be overridden when the configuration is deployed.";

    @Override
    public JOCDefaultResponse deploy(final String accessToken, final byte[] filterBytes) {
        SOSHibernateSession session = null;
        try {
            JsonValidator.validateFailFast(filterBytes, DeployConfiguration.class);
            DeployConfiguration in = Globals.objectMapper.readValue(filterBytes, DeployConfiguration.class);
            
            if (in.getObjectType() != null && in.getObjectType().equals(ObjectType.OTHER)) {
                throw new JocException(new JocError(JocXmlEditor.ERROR_CODE_DEPLOY_ERROR_UNSUPPORTED_OBJECT_TYPE, String.format(
                        "[%s][%s]unsupported object type for deployment", in.getJobschedulerId(), in.getObjectType().name())));
            }
            // TODO check folder permissions
            checkRequiredParameters(in);

            JOCDefaultResponse response = checkPermissions(accessToken, in);
            if (response == null) {
                XmlEditorAudit audit = new XmlEditorAudit(in);
                logAuditMessage(audit);

                // step 1 - check for vulnerabilities and validate
                XsdValidator validator = new XsdValidator(JocXmlEditor.getStandardAbsoluteSchemaLocation(in.getObjectType()));
                try {
                    validator.validate(in.getConfiguration());
                } catch (XsdValidatorException e) {
                    LOGGER.error(String.format("[%s]%s", validator.getSchema(), e.toString()), e);
                    return JOCDefaultResponse.responseStatus200(ValidateResourceImpl.getError(e));
                }

                session = Globals.createSosHibernateStatelessConnection(IMPL_PATH);
                DbLayerXmlEditor dbLayer = new DbLayerXmlEditor(session);

                // step 2 - store draft in the database
                DBItemXmlEditorObject item = getItem(dbLayer, in);

                // step 3 - deploy
                Map<Date, String> result = putFile(in, item.getConfigurationDraft());

                // step 4 - update db
                Date deployed = result.keySet().iterator().next();
                audit.setStartTime(deployed);
                DBItemAuditLog auditItem = storeAuditLogEntry(audit);
                if (auditItem != null) {
                    item.setAuditLogId(auditItem.getId());
                }
                item.setConfigurationDeployed(result.get(deployed));
                item.setConfigurationDeployedJson(item.getConfigurationDraftJson());
                item.setConfigurationDraft(null);
                item.setConfigurationDraftJson(null);
                item.setAccount(getAccount());
                item.setDeployed(deployed);
                item.setModified(new Date());

                session.beginTransaction();
                session.update(item);
                session.commit();
                response = JOCDefaultResponse.responseStatus200(getSuccess(deployed));
            }
            return response;
        } catch (JocException e) {
            Globals.rollback(session);
            e.addErrorMetaInfo(getJocError());
            return JOCDefaultResponse.responseStatusJSError(e);
        } catch (Exception e) {
            Globals.rollback(session);
            return JOCDefaultResponse.responseStatusJSError(e, getJocError());
        } finally {
            Globals.disconnect(session);
        }
    }

    private void checkRequiredParameters(final DeployConfiguration in) throws Exception {
        checkRequiredParameter("jobschedulerId", in.getJobschedulerId());
        JocXmlEditor.checkRequiredParameter("objectType", in.getObjectType());
        checkRequiredParameter("configuration", in.getConfiguration());
        checkRequiredParameter("configurationJson", in.getConfigurationJson());
    }

    private JOCDefaultResponse checkPermissions(final String accessToken, final DeployConfiguration in) throws Exception {
        SOSPermissionJocCockpit permissions = getPermissonsJocCockpit(in.getJobschedulerId(), accessToken);
        boolean permission = permissions.getJobschedulerMaster().getAdministration().getConfigurations().getDeploy().isXmlEditor();
        JOCDefaultResponse response = init(IMPL_PATH, in, accessToken, in.getJobschedulerId(), permission);
        if (response == null) {
            if (versionIsOlderThan(JocXmlEditor.AVAILABILITY_STARTING_WITH)) {
                throw new JobSchedulerBadRequestException(JocXmlEditor.MESSAGE_UNSUPPORTED_WEB_SERVICE);
            }
        }
        return response;
    }

    private DBItemXmlEditorObject getItem(DbLayerXmlEditor dbLayer, DeployConfiguration in) throws Exception {
        dbLayer.getSession().beginTransaction();
        DBItemXmlEditorObject item = dbLayer.getObject(in.getJobschedulerId(), in.getObjectType().name(), JocXmlEditor.getConfigurationName(in
                .getObjectType()));
        if (item == null) {
            item = new DBItemXmlEditorObject();
            item.setSchedulerId(in.getJobschedulerId());
            item.setObjectType(in.getObjectType().name());
            item.setName(JocXmlEditor.getConfigurationName(in.getObjectType()));
            item.setConfigurationDraft(in.getConfiguration());
            item.setConfigurationDraftJson(in.getConfigurationJson());
            item.setSchemaLocation(JocXmlEditor.getStandardRelativeSchemaLocation(in.getObjectType()));

            item.setAuditLogId(new Long(0));// TODO
            item.setAccount(getAccount());
            item.setCreated(new Date());
            item.setModified(item.getCreated());
            dbLayer.getSession().save(item);
        } else {
            item.setConfigurationDraft(in.getConfiguration());
            item.setConfigurationDraftJson(in.getConfigurationJson());
            item.setAccount(getAccount());
            item.setModified(new Date());
            dbLayer.getSession().update(item);
        }
        dbLayer.getSession().commit();
        return item;
    }

    private DeployConfigurationAnswer getSuccess(Date deployed) {
        DeployConfigurationAnswer answer = new DeployConfigurationAnswer();
        answer.setDeployed(deployed);
        answer.setMessage(new AnswerMessage());
        answer.getMessage().setCode(JocXmlEditor.MESSAGE_CODE_DRAFT_NOT_EXIST);
        answer.getMessage().setMessage(JocXmlEditor.MESSAGE_DRAFT_NOT_EXIST);
        return answer;
    }

    private Map<Date, String> putFile(DeployConfiguration in, String configuration) throws Exception {
        String file = null;// for exception
        try {
            JOCHotFolder hotFolder = new JOCHotFolder(this);
            Date deployed = new Date();
            String deployedDateTime = "unknown";
            try {
                deployedDateTime = SOSDate.getDateAsString(deployed, "yyyy-MM-dd HH:mm:ss");
            } catch (Exception e) {
            }

            String content = getXmlFileContent(in.getObjectType(), configuration, deployedDateTime);
            file = JocXmlEditor.getJobSchedulerLivePathXml(in.getObjectType());
            hotFolder.putFile(file, content.getBytes(JocXmlEditor.CHARSET));
            if (in.getObjectType().equals(ObjectType.YADE)) {
                file = JocXmlEditor.getJobSchedulerLivePathYadeIni();
                hotFolder.putFile(file, convertXml2Ini(configuration, deployedDateTime));
            }
            return Collections.singletonMap(deployed, content);
        } catch (Throwable e) {
            LOGGER.error(String.format("[%s][%s][%s]%s could't put configuration: %s", in.getJobschedulerId(), in.getObjectType().name(), file,
                    JocXmlEditor.ERROR_CODE_DEPLOY_ERROR, e.toString()), e);
            throw new JocException(new JocError(JocXmlEditor.ERROR_CODE_DEPLOY_ERROR, String.format(
                    "[%s]Could't put configuration. Is the JobScheduler \"%s\" running?", file, in.getJobschedulerId())));
        }
    }

    private String getXmlFileContent(ObjectType objectType, String configuration, String deployedDateTime) throws Exception {
        StringBuilder sb = getXmlFileHeader(objectType, deployedDateTime);
        int indx = -1;
        if (objectType.equals(ObjectType.YADE)) {
            indx = configuration.indexOf(JobSchedulerXmlEditor.SCHEMA_ROOT_ELEMENT_NAME_YADE);
        } else {
            indx = configuration.indexOf(JobSchedulerXmlEditor.SCHEMA_ROOT_ELEMENT_NAME__NOTIFICATION);
        }
        if (indx > -1) {
            configuration = configuration.substring(indx - 1);
        }
        return sb.append(configuration).toString();
    }

    private byte[] convertXml2Ini(String configuration, String deployedDateTime) throws Exception {
        JadeXml2IniConverter converter = new JadeXml2IniConverter();
        InputSource schemaInputSource = new InputSource(Files.newInputStream(JocXmlEditor.getStandardAbsoluteSchemaLocation(ObjectType.YADE)));
        InputSource configurationInputSource = new InputSource();
        configurationInputSource.setCharacterStream(new StringReader(configuration));
        return converter.process(schemaInputSource, configurationInputSource, getIniFileHeader(deployedDateTime));
    }

    private StringBuilder getIniFileHeader(String deployedDateTime) {
        StringBuilder sb = new StringBuilder("###########################################################").append(JadeXml2IniConverter.NEW_LINE);
        sb.append("# ").append(String.format(DEPLOY_HEADER, deployedDateTime)).append(JadeXml2IniConverter.NEW_LINE);
        sb.append("# ").append(String.format(DEPLOY_HEADER_MESSAGE, ObjectType.YADE.name())).append(JadeXml2IniConverter.NEW_LINE);
        sb.append("###########################################################");
        return sb;
    }

    private StringBuilder getXmlFileHeader(ObjectType objectType, String deployedDateTime) {
        StringBuilder sb = new StringBuilder(JocXmlEditor.XML_DECLARATION).append(JocXmlEditor.NEW_LINE);
        sb.append("<!-- ").append(String.format(DEPLOY_HEADER, deployedDateTime)).append(" -->").append(JocXmlEditor.NEW_LINE);
        sb.append("<!-- ").append(String.format(DEPLOY_HEADER_MESSAGE, objectType.name())).append(" -->").append(JocXmlEditor.NEW_LINE);
        return sb;
    }

}
