type: error
post:
  description: |
    <h2>Log (plain text or html)</h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``jobschedulerId``</td><td>required, string</td><td>JobScheduler Master ID</td><td>scheduler</td><td></td></tr>
    <<description1>>
    <<description2>>
    <<description3>>
    <tr><td>``mime``</td><td>optional, string,<br/>enum[PLAIN,HTML]</td><td>The log can have a HTML representation where the HTML content is a colored version consider the log levelfor the browser where CSS is required.<br/>
    <pre>
      pre.log                         {font-family:"Lucida Console",monospace;font-size:12px;line-height:1.1em;margin-left:2px;padding-left:0}
      .log_error                      {color:red;}
      .log_warn                       {color:tomato;}
      .log_info                       {color:black;}
      .log_stderr                     {color:red;}
      .log_debug                      {color:darkgreen;}
      .log_debug2                     {color:#408040;}
      .log_debug3                     {color:#808080;}
      .log_debug4                     {color:#8080FF;}
      .log_debug5                     {color:#8080FF;}
      .log_debug6                     {color:#8080FF;}
      .log_debug7                     {color:#8080FF;}
      .log_debug8                     {color:#8080FF;}
      .log_debug9                     {color:#a0a0a0;}
    </pre>
    </td><td></td><td>PLAIN</td></tr>
    <tr><td>``filename``</td><td>optional, string</td><td>name of a temp. file from ./<<objecttype>><<resourcePath>>/info<br/>This file will be responsed if exists</td><td>sos-download-5961566003164029224.tmp</td><td></td></tr>
    </tbody></table>

  body:
    application/json:
      schema: <<schema>>
      example: <<example>>
  responses:
    200:
      description: Content of log. It depends on the if size if it is offered as download with the Content-Disposition header
      headers:
        Content-Disposition:
          type: string
          required: false
          example: attachment;filename=xxx.<<objecttype>>.log
        Content-Type:
          type: string
          required: true
          default: text/plain
      body:
        application/octet-stream:
        text/plain:
      #description: <<description200>>
      #body:
      #  application/json:
      #    schema: logContent
      #    example: <<example200>>
    420:
      body:
        application/json:
    440:
      body:
        application/json:
