//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.24 at 11:34:46 AM CEST 
//


package com.sos.auth.rest.permission.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{}SOSPermissionCommandsMaster"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sosPermissionCommandsMaster"
})
@XmlRootElement(name = "SOSPermissionCommandsMasters")
public class SOSPermissionCommandsMasters
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "SOSPermissionCommandsMaster", required = true)
    protected List<SOSPermissionCommandsMaster> sosPermissionCommandsMaster;

    /**
     * Gets the value of the sosPermissionCommandsMaster property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sosPermissionCommandsMaster property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSOSPermissionCommandsMaster().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SOSPermissionCommandsMaster }
     * 
     * 
     */
    public List<SOSPermissionCommandsMaster> getSOSPermissionCommandsMaster() {
        if (sosPermissionCommandsMaster == null) {
            sosPermissionCommandsMaster = new ArrayList<SOSPermissionCommandsMaster>();
        }
        return this.sosPermissionCommandsMaster;
    }

    public boolean isSetSOSPermissionCommandsMaster() {
        return ((this.sosPermissionCommandsMaster!= null)&&(!this.sosPermissionCommandsMaster.isEmpty()));
    }

    public void unsetSOSPermissionCommandsMaster() {
        this.sosPermissionCommandsMaster = null;
    }

}
