type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``jobschedulerId``</td><td>required, string</td><td>JobScheduler Master ID</td><td>scheduler</td><td></td></tr>
    <tr><td>``host``</td><td>optional, string</td><td>host of the JobScheduler Master<br/><b>This parameter is required to check the state of the JobScheduler after a command such as terminate, pause, abort, etc.</b></td><td>localhost</td><td></td></tr>
    <tr><td>``port``</td><td>optional, string</td><td>port of the JobScheduler Master<br/><b>This parameter is required to check the state of the JobScheduler after a command such as terminate, pause, abort, etc.</b></td><td>4444</td><td></td></tr>
    </tbody></table>
  body:
    application/json:
      schema: jsFilterWithUrl
      example: |
        {
          "jobschedulerId": "scheduler"
        }
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          example: <<example200>>
          schema: <<schema200>>
